# Downloading and Prepping data for Projecting Bat Speed 

This file
- Pulls data from statcast via pybaseball
- Pulls player bio data from MLB

## Preparing the data

In [1]:
import os
from tqdm import tqdm
from datetime import datetime
import pandas as pd
import numpy as np
import requests

import pybaseball as pb

import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

# for reproducibility
print("pandas: "+pd.__version__)
print("numpy: "+np.__version__)
print("pybaseball: "+pb.__version__)
pb.cache.enable()

pandas: 3.0.1
numpy: 2.4.3
pybaseball: 2.2.7

Here we create some helper functions to download the data from statcast. The logic is we only need to download data from 2016 to last year once, it won't change. However, when we are in-season, we want to keep updating our local data. Therefore, when we first collect data, we set a flag called `get_prior_year=True`. This flag tells the script to pull the data from statcast, roughly 2 minutes per season. After it downloads the data, it saves a local version of it in a new folder called `statcast_data/statcast_{year}`. When the flag is set to false, the process will load the data from the local file location.

We also have a function to grab player bio from the statsapi.mlb.com/api.

In [2]:
def get_statcast_data_year(year:int):
    return pb.statcast(start_dt=f'{year}-03-01', end_dt=f'{year}-10-31')

def get_year(path: str, year: int, refresh: bool):
    os.makedirs(path, exist_ok=True)
    file_path = os.path.join(path, f"statcast_{year}.csv")
    if refresh:
        print(f'pulling data for {year}')
        df = get_statcast_data_year(year)
        df.to_csv(file_path, index=False)
        return df
    else:
        print(f'loading data for {year}')
        return pd.read_csv(file_path, low_memory=False)

def get_statcast_data(get_prior_years:bool=False, path="statcast_data"):
    df_list = []
    curr_year = datetime.now().year
    curr_month = datetime.now().month
    in_season = curr_month <= 10
    for year in range(2016, curr_year):
        df_list.append(get_year(path, year, refresh=get_prior_years))

    df_list.append(get_year(path, curr_year, refresh=in_season))

    return pd.concat(df_list, ignore_index=True)

def get_player_bio(ids):
    data = []
    for pid in tqdm(ids):
        r = requests.get(f'https://statsapi.mlb.com/api/v1/people/{pid}').json()
        if r['people']:
            p = r['people'][0]
            data.append({
                'bam_id': pid,
                'full': p['nameFirstLast'],
                'first': p['useName'],
                'last': p['useLastName'],
                'bats': p['batSide']['code'],
                'position': p['primaryPosition']['abbreviation'],
                'birth_date': p['birthDate'],
                'birthCity': p.get('birthCity'),
                'birthState': p.get('birthStateProvince'),
                'birthCountry': p.get('birthCountry')
            })
    d = pd.DataFrame(data)
    return d

In [3]:
# Now pull data. We flip to False since we have the data.
data = get_statcast_data(get_prior_years=False)

loading data for 2016
loading data for 2017
loading data for 2018
loading data for 2019
loading data for 2020
loading data for 2021
loading data for 2022
loading data for 2023
loading data for 2024
loading data for 2025
pulling data for 2026
This is a large query, it may take a moment to complete
Skipping offseason dates

100%|██████████| 231/231 [02:22<00:00,  1.62it/s]

In [4]:
# sv_id column caused some warnings when reading the file, dropping it for ease.
data = data.drop(['sv_id'],axis=1)

In [5]:
# make a month name variable
month_map = {
    3: 'Mar/Apr', 4: 'Mar/Apr',
    5: 'May', 6: 'Jun',
    7: 'Jul', 8: 'Aug',
    9: 'Sep/Oct', 10: 'Sep/Oct',
}
data['game_date'] = pd.to_datetime(data['game_date'])
data['month_number']=data['game_date'].dt.month
data['year']=data['game_date'].dt.year
data['month_name']=data['month_number'].map(month_map)
data['month_name'] = pd.Categorical(data['month_name'], categories=['Mar/Apr','May','Jun','Jul','Aug','Sep/Oct'], ordered=True)

In [6]:
# After downloading and loading the data, clean it up
# filter to regular season
data = data.loc[data['game_type'].isin(['R'])].reset_index(drop=True)
bs = data.loc[~data['bat_speed'].isna()]
bs50 = data.loc[data['bat_speed']>=50]
print(round((1-bs50.shape[0]/bs.shape[0])*100,1))

data.loc[~data['bat_speed'].isna()]['bat_speed'].describe(percentiles=[.005, .01, .05, .1, .25, .5, .75, .95])

3.4

count    1052372.0
mean     69.623512
std       9.149053
min            0.3
0.5%          12.6
1%            29.0
5%            56.6
10%           62.2
25%           67.2
50%           71.2
75%           74.5
95%           79.1
max           88.0
Name: bat_speed, dtype: Float64

In [7]:
# is_swing flag
is_swing_description = [
    'hit_into_play',
    'foul',
    'swinging_strike_blocked',
    'swinging_strike',
    'foul_tip',
    'foul_bunt',
    'missed_bunt',
    'bunt_foul_tip',
    'foul_pitchout',
    'swinging_pitchout'
]
data['is_swing'] = data['description'].isin(is_swing_description).astype(int)
data.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,...,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches,month_number,year,month_name,is_swing
0,FF,2016-10-02,96.4,-0.53,6.23,"Osuna, Roberto",598265,532077,field_out,hit_into_play,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10,2016,Sep/Oct,1
1,FF,2016-10-02,96.8,-0.35,6.34,"Osuna, Roberto",598265,532077,NaN,called_strike,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10,2016,Sep/Oct,0
2,SI,2016-10-02,96.7,-0.56,6.22,"Osuna, Roberto",593428,532077,single,hit_into_play,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10,2016,Sep/Oct,1
3,FF,2016-10-02,97.0,-0.48,6.28,"Osuna, Roberto",593428,532077,NaN,called_strike,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10,2016,Sep/Oct,0
4,FF,2016-10-02,93.6,-0.54,6.23,"Osuna, Roberto",593428,532077,NaN,ball,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10,2016,Sep/Oct,0

In [8]:
# sanity check
# everywhere there is bat speed, is_swing should be 1
data.loc[data['bat_speed'].notna() & (data['is_swing'] == 0)]

Empty DataFrame
Columns: [pitch_type, game_date, release_speed, release_pos_x, release_pos_z, player_name, batter, pitcher, events, description, spin_dir, spin_rate_deprecated, break_angle_deprecated, break_length_deprecated, zone, des, game_type, stand, p_throws, home_team, away_team, type, hit_location, bb_type, balls, strikes, game_year, pfx_x, pfx_z, plate_x, plate_z, on_3b, on_2b, on_1b, outs_when_up, inning, inning_topbot, hc_x, hc_y, tfs_deprecated, tfs_zulu_deprecated, umpire, vx0, vy0, vz0, ax, ay, az, sz_top, sz_bot, hit_distance_sc, launch_speed, launch_angle, effective_speed, release_spin_rate, release_extension, game_pk, fielder_2, fielder_3, fielder_4, fielder_5, fielder_6, fielder_7, fielder_8, fielder_9, release_pos_y, estimated_ba_using_speedangle, estimated_woba_using_speedangle, woba_value, woba_denom, babip_value, iso_value, launch_speed_angle, at_bat_number, pitch_number, pitch_name, home_score, away_score, bat_score, fld_score, post_away_score, post_home_score, post_bat_score, post_fld_score, if_fielding_alignment, of_fielding_alignment, spin_axis, delta_home_win_exp, delta_run_exp, bat_speed, swing_length, miss_distance, estimated_slg_using_speedangle, delta_pitcher_run_exp, hyper_speed, home_score_diff, bat_score_diff, home_win_exp, bat_win_exp, age_pit_legacy, ...]
Index: []

[0 rows x 122 columns]

In [9]:
# assuming any bat speed below 50 is a missread/non-competitive
data['bat_speed'] = data['bat_speed'].mask(data['bat_speed'] < 50)
for c in ['launch_speed','release_speed','bat_speed']:
    data[c] = data[c].astype(float)

In [10]:
# download player bio
player_ids = pd.unique(data['batter'])
player_bio = get_player_bio(player_ids)
player_bio.to_csv('player_bio.csv', index=False)

100%|██████████| 2606/2606 [07:48<00:00,  5.56it/s]

In [11]:
data.to_csv('agg_data.csv', index=False)